In [6]:
import pandas as pd
from jaqs_fxdayu.util import dp
from jaqs.data.dataapi import DataApi
import numpy as np
import talib as ta
from jaqs_fxdayu.research.signaldigger.process import neutralize


api = DataApi(addr='tcp://data.tushare.org:8910')
api.login("13662241013", 
          'eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MTc2NDQzMzg5MTIiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTM2NjIyNDEwMTMifQ.sVIzI5VLqq8fbZCW6yZZW0ClaCkcZpFqpiK944AHEow'
)
start = 20130101
end = 20180101
SH_id = dp.index_cons(api, "000300.SH", start, end)
SZ_id = dp.index_cons(api, "000905.SH", start, end)
stock_symbol = list(set(SH_id.symbol)|set(SZ_id.symbol))

In [7]:
#读取数据，其中需要调节我们需要的因子的数量和内容
factor_list = ['oper_rev','oper_rev_ttm','oper_rev_lyr',"total_oper_rev",'less_gerl_admin_exp','AdminiExpenseRate','volume',"gainvariance120",'index',"cash_recp_sg_and_rs"]
check_factor = ','.join(factor_list)


import jaqs_fxdayu
jaqs_fxdayu.patch_all()
from jaqs.data import DataView
from jaqs.data import RemoteDataService
from jaqs_fxdayu.data.dataservice import LocalDataService
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")

dataview_folder = 'E:/data'
dv = DataView()
ds = LocalDataService(fp=dataview_folder)

dv_props = {'start_date': start, 'end_date': end, 'symbol':','.join(stock_symbol),
         'fields': check_factor,
         'freq': 1,
         "prepare_fields": True}

dv.init_from_config(dv_props, data_api=ds)
dv.prepare_data()

Field name [{'index', 'gainvariance120'}] not valid, ignore.
Initialize config success.
Query data...
Query data - query...
NOTE: price adjust method is [post adjust]
当前请求daily...
{'adjust_mode': None, 'fields': 'trade_status,vwap,low_adj,high,trade_date,open,close,close_adj,open_adj,symbol,low,vwap_adj,high_adj,volume'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
当前请求daily...
{'adjust_mode': 'post', 'fields': 'vwap,high,open,close,low,symbol,trade_date'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
当前请求query_lb_dailyindicator...
{'fields': 'oper_rev_lyr,oper_rev_ttm,trade_date,symbol'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
当前请求query...
{'fields': 'AdminiExpenseRate', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - quarterly fields prepared.
Query instrument info...
Query adj_factor...
Data has been successfully prepared.

In [8]:
#获取行业情况
dv.add_field('sw1')
sw1 = dv.get_ts('sw1')
dict_classify = {'480000': '银行', '430000': '房地产', '460000': '休闲服务', '640000': '机械设备', '240000': '有色金属', '510000': '综合', '410000': '公用事业', '450000': '商业贸易', '730000': '通信', '330000': '家用电器', '720000': '传媒', '630000': '电气设备', '270000': '电子', '490000': '非银金融', '370000': '医药生物', '710000': '计算机', '280000': '汽车', '340000': '食品饮料', '220000': '化工', '210000': '采掘', '230000': '钢铁', '650000': '国防军工', '110000': '农林牧渔', '420000': '交通运输', '620000': '建筑装饰', '350000': '纺织服装', '610000': '建筑材料', '360000': '轻工制造'}
sw1_name = sw1.replace(dict_classify)
sw1_name.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171226,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171227,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171228,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171229,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属

In [10]:
#gainvariance120
def cal_positive(df):
    return df[df>0]
pct_return = cal_positive(dv.get_ts('close').pct_change())
temp = pd.DataFrame({name:value.dropna().rolling(120).std()**2 for name,value in pct_return.iteritems()}, index=pct_return.index).fillna(method='ffill')
dv.append_df(temp,'gainvariance120')
temp.tail()

Field [gainvariance120] is overwritten.

,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,0.000205,0.000533,0.000245,0.000133,0.000143,0.000167,0.000117,NaN,0.000583,0.000101,...,NaN,0.000114,0.000127,0.000265,NaN,0.000144,0.000111,0.000399,0.000136,0.000695
20171226,0.000208,0.000534,0.000245,0.000135,0.000143,0.000167,0.000117,NaN,0.000581,0.000101,...,NaN,0.000115,0.000127,0.000265,NaN,0.000149,0.000111,0.000398,0.000136,0.000695
20171227,0.000208,0.000534,0.000245,0.000135,0.000144,0.000167,0.000117,NaN,0.000581,0.000101,...,NaN,0.000115,0.000127,0.000265,0.000422,0.000149,0.000111,0.000398,0.000136,0.000694
20171228,0.000208,0.000534,0.000245,0.000135,0.000144,0.000167,0.000118,NaN,0.000582,0.000101,...,NaN,0.000115,0.000127,0.000266,0.000369,0.000149,0.000111,0.000398,0.000136,0.000705
20171229,0.000208,0.000531,0.000245,0.000135,0.000143,0.000171,0.000119,NaN,0.000583,0.000100,...,NaN,0.000115,0.000127,0.000265,0.000369,0.000152,0.000114,0.000397,0.000138,0.000705

In [11]:
#alpha46
def mean(df,day):
    return df.rolling(window=day,center=False).mean()  
alpha46 = dv.add_formula('alpha46', 
               "(mean(close,3)+mean(close,6)+mean(close,12)+mean(close,24))/(4*close)",
               is_quarterly=False,
               add_data=True,
               register_funcs={"mean":mean})
alpha46.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,1.005825,0.982439,1.0,0.995195,1.011463,1.036806,1.012048,NaN,1.032146,1.001891,...,0.977993,1.021347,1.008285,0.981374,1.044092,0.980509,0.992776,1.036807,1.001103,1.017857
20171226,0.978915,0.982951,1.0,0.973833,1.008330,1.018251,0.995405,NaN,1.015794,1.000532,...,0.998286,0.997320,0.997617,0.986928,1.027995,0.950686,0.975489,1.008746,1.000926,1.018692
20171227,1.003598,0.978852,1.0,0.980337,1.005208,1.023990,1.023927,NaN,1.014486,1.003604,...,1.003708,1.014322,1.004930,1.007114,1.006456,0.989246,0.993557,1.025768,1.013195,0.998174
20171228,1.008501,0.985861,1.0,0.989932,1.007109,1.017361,0.998039,NaN,1.012587,1.004681,...,1.012685,1.016791,1.006586,1.000762,0.978060,1.003279,0.983457,1.008089,1.013459,0.945405
20171229,0.998441,0.978332,1.0,0.982714,1.000490,0.987821,0.977754,NaN,1.009419,0.999656,...,1.002705,1.008743,1.002053,0.977133,0.989226,0.972504,0.958333,1.003044,0.985646,0.972005

In [12]:
#alpha48
def sum_fxdayu(df,day):
    return df.rolling(window=day,center=False).sum()  
alpha48 = dv.add_formula('alpha48', 
               "(-1*((Rank(((Sign((close - Delay(close, 1))) + Sign((Delay(close, 1) - Delay(close, 2)))) +Sign((Delay(close, 2) - Delay(close, 3)))))) * SUM(volume, 5)) / SUM(volume, 20))",
               is_quarterly=False,
               add_data=True,
               register_funcs={"SUM":sum_fxdayu})
alpha48.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,-66.082124,-239.181103,NaN,-206.416573,-63.087123,-103.175698,-74.508096,NaN,-0.198105,-256.946818,...,-164.406818,-152.257166,-134.678705,-205.895001,-57.050444,-155.082238,-273.655157,-0.245041,-72.387666,-103.214198
20171226,-22.740065,-235.861563,NaN,-316.190646,-180.439651,-96.650336,-29.047387,NaN,-20.596744,-246.560297,...,-24.435002,-161.184727,-111.205948,-27.124612,-17.737776,-186.623167,-248.290869,-22.682690,-0.298688,-12.887165
20171227,-26.095407,-263.126408,NaN,-227.885687,-201.681640,-15.169630,-31.220487,NaN,-23.671279,-38.052645,...,-29.327095,-27.923432,-17.078215,-29.472422,-141.628008,-229.050510,-35.448133,-23.987547,-0.327118,-130.766751
20171228,-23.106251,-120.407831,NaN,-33.205686,-148.483487,-76.924590,-132.333586,NaN,-115.322646,-33.760822,...,-0.277287,-27.743877,-15.317158,-25.794254,-200.776115,-30.778013,-159.447121,-105.061516,-0.314547,-148.455179
20171229,-15.416523,-132.635483,NaN,-23.352186,-144.773504,-105.925311,-145.908430,NaN,-123.698958,-16.176847,...,-19.246576,-17.231856,-10.494582,-130.238772,-137.727449,-20.470706,-177.038420,-111.596935,-21.715150,-170.260124

In [13]:
#alpha85
alpha85 = dv.add_formula('alpha85', 
               "(Ts_Rank((volume / mean(volume,20)), 20) * Ts_Rank((-1 * Delta(close, 7)), 8))",
               is_quarterly=False,
               add_data=True,
               register_funcs={"mean":mean})
alpha85.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,54.0,17.0,NaN,26.0,75.0,56.0,136.0,NaN,48.0,126.0,...,160.0,49.0,24.0,72.0,104.0,120.0,160.0,72.0,144.0,16.0
20171226,12.0,2.0,NaN,19.0,20.0,1.0,77.0,NaN,60.0,64.0,...,160.0,17.0,8.0,48.0,28.0,60.0,56.0,35.0,140.0,16.0
20171227,34.0,13.0,NaN,36.0,24.0,4.0,104.0,NaN,78.0,48.0,...,96.0,126.0,30.0,88.0,80.0,112.0,84.0,98.0,133.0,54.0
20171228,126.0,26.0,NaN,85.0,38.0,13.0,98.0,NaN,126.0,96.0,...,136.0,126.0,35.0,152.0,95.0,48.0,77.0,40.0,112.0,20.0
20171229,54.0,15.0,NaN,54.0,7.0,20.0,64.0,NaN,3.0,20.0,...,42.0,7.0,6.0,102.0,36.0,60.0,36.0,10.0,54.0,18.0

In [14]:
#VEMA12   直接计算一个dataframe 吧没有开盘的数据drop然后再相加，最后加回来，会损失一部分样本（100余支股票，是在报告期内有停牌过的股票）
volume=dv.get_ts("volume")
volume=volume.dropna(axis=1)
vema12=pd.DataFrame(index=volume.index)
for col in volume.columns:
    inter=pd.DataFrame(pd.Series(ta.EMA(np.array(list(volume[col])),12)),columns=[col])
    for i in range(1215):
        vema12.loc[vema12.index[i],col]=inter.iloc[i,0]
temp=[]
test=list(vema12.columns)
for i in stock_symbol:
    if i not in test:
        temp=temp+[i]
for i in temp:
    vema12[i]=np.nan
dv.append_df(vema12,"vema12")
vema12.tail()

,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,603169.SH,603699.SH,300376.SZ,000688.SZ,603377.SH,603355.SH,601226.SH,000562.SZ,603833.SH,000748.SZ
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,1.399170e+08,4.505517e+07,353.927896,5.808936e+06,1.391675e+07,2.242965e+07,2.107117e+07,1.596487e+06,6.234044e+06,1.649664e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171226,1.356788e+08,4.241353e+07,299.477451,6.620027e+06,1.335422e+07,2.059474e+07,2.019655e+07,1.570351e+06,5.957847e+06,1.591794e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171227,1.358292e+08,4.197282e+07,253.403997,7.296915e+06,1.329402e+07,1.894670e+07,1.980115e+07,1.541075e+06,5.742784e+06,1.680095e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171228,1.388252e+08,4.116648e+07,214.418767,7.574742e+06,1.420589e+07,1.794519e+07,1.960075e+07,1.552131e+06,5.605438e+06,1.754167e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171229,1.325893e+08,4.076098e+07,181.431264,8.290919e+06,1.392032e+07,2.102770e+07,1.987988e+07,1.463221e+06,5.345048e+06,1.713894e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#informationratio60
hs300=ds.index_daily(['000300.SH'],20130101,20180101,"close")[0].pct_change()
close=dv.get_ts("close")
hs300=hs300.set_index(close.index)
hs300=hs300['close']
close=close.dropna(axis=1)
close=close.pct_change()
close=close.sub(hs300,axis=0)   #计算出了每日的超额收益,下面计算60日IC
ret=close.rolling(window=60).mean()
std=close.rolling(window=60).std()
ir60=close.copy()
for col in ir60.columns:
    ir60[col]=ret[col].div(std[col],axis=0)#计算出60日信息比率
dv.append_df(ir60,"ir60")
ir60.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,601991.SH,601992.SH,601998.SH,601999.SH,603000.SH,603001.SH,603077.SH,603366.SH,603766.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,0.099880,0.073917,-0.126018,-0.098519,-0.290967,-0.057309,-0.016775,-0.147028,-0.192393,-0.185596,...,-0.192195,-0.203174,-0.142471,-0.211557,-0.293049,-0.330693,-0.316992,-0.246332,-0.234678,-0.107370
20171226,0.141877,0.059915,-0.130677,-0.052506,-0.305228,-0.047372,-0.002616,-0.143779,-0.196105,-0.181905,...,-0.195762,-0.220610,-0.128694,-0.203825,-0.277418,-0.323520,-0.288042,-0.225231,-0.187154,-0.120977
20171227,0.141208,0.073611,-0.094022,-0.026546,-0.293266,-0.043808,-0.025851,-0.129242,-0.175873,-0.139514,...,-0.193371,-0.199494,-0.104357,-0.201997,-0.275337,-0.300852,-0.278468,-0.229819,-0.193634,-0.119041
20171228,0.133902,0.077970,-0.107123,-0.039889,-0.298421,-0.039618,-0.018208,-0.108407,-0.203498,-0.144936,...,-0.182318,-0.181697,-0.114635,-0.202981,-0.268625,-0.295031,-0.260285,-0.228541,-0.195592,-0.076834
20171229,0.123040,0.089927,-0.105774,-0.081427,-0.289216,-0.016269,-0.003002,-0.113496,-0.188900,-0.157700,...,-0.231109,-0.217399,-0.105730,-0.200126,-0.266435,-0.294073,-0.289006,-0.209810,-0.185929,-0.093015

In [16]:
#adminiexpenserate
adminiexpenserate = dv.add_formula('adminiexpenserate', 
               "TTM(less_gerl_admin_exp)/TTM(total_oper_rev)",
               is_quarterly=False,
               add_data=True)
adminiexpenserate.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20171229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#ssctol
ssctol= dv.add_formula('ssctol', 
               "cash_recp_sg_and_rs/oper_rev",
               is_quarterly=False,
               add_data=True)
ssctol.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,0.0,2.099977,1.064299,NaN,1.124373,1.118784,0.875728,NaN,1.076793,1.040339,...,1.133472,1.18663,1.120543,1.167563,1.119478,1.227298,1.169313,0.923475,1.114374,0.984202
20171226,0.0,2.099977,1.064299,NaN,1.124373,1.118784,0.875728,NaN,1.076793,1.040339,...,1.133472,1.18663,1.120543,1.167563,1.119478,1.227298,1.169313,0.923475,1.114374,0.984202
20171227,0.0,2.099977,1.064299,NaN,1.124373,1.118784,0.875728,NaN,1.076793,1.040339,...,1.133472,1.18663,1.120543,1.167563,1.119478,1.227298,1.169313,0.923475,1.114374,0.984202
20171228,0.0,2.099977,1.064299,NaN,1.124373,1.118784,0.875728,NaN,1.076793,1.040339,...,1.133472,1.18663,1.120543,1.167563,1.119478,1.227298,1.169313,0.923475,1.114374,0.984202
20171229,0.0,2.099977,1.064299,NaN,1.124373,1.118784,0.875728,NaN,1.076793,1.040339,...,1.133472,1.18663,1.120543,1.167563,1.119478,1.227298,1.169313,0.923475,1.114374,0.984202

In [18]:
#数据预处理
id_zz500 = dp.daily_index_cons(api, "000300.SH", start, end)
id_hs300 = dp.daily_index_cons(api, "000905.SH", start, end)
columns_500 = list(set(id_zz500.columns)-set(id_hs300.columns))
id_member = pd.concat([id_zz500[columns_500],id_hs300],axis=1)
mask = ~id_member
# 定义可买卖条件——未停牌、未涨跌停
def limit_up_down():
    trade_status = dv.get_ts('trade_status').fillna(0)
    mask_sus = trade_status == 0
    # 涨停
    up_limit = dv.add_formula('up_limit', '(close - Delay(close, 1)) / Delay(close, 1) > 0.095', is_quarterly=False)
    # 跌停
    down_limit = dv.add_formula('down_limit', '(close - Delay(close, 1)) / Delay(close, 1) < -0.095', is_quarterly=False)
    can_enter = np.logical_and(up_limit < 1, ~mask_sus) # 未涨停未停牌
    can_exit = np.logical_and(down_limit < 1, ~mask_sus) # 未跌停未停牌
    return can_enter,can_exit
can_enter,can_exit = limit_up_down()
alpha_signal = ['gainvariance120','alpha46','alpha48','alpha85',"vema12","ir60",'adminiexpenserate','ssctol']
price = dv.get_ts('close_adj')
sw1 = sw1_name
enter = can_enter
exit =  can_exit
mask = mask
from jaqs_fxdayu.research.signaldigger.process import neutralize
neutralize_dict = {a: neutralize(factor_df = dv.get_ts(a), group = dv.get_ts("sw1")) for a in alpha_signal}

In [19]:
#分析因子所在行业特点
import matplotlib.pyplot as plt
from jaqs_fxdayu.research import SignalDigger
from jaqs_fxdayu.research.signaldigger import analysis
def cal_obj(signal, name, period, quantile):
#     price_bench = dv.data_benchmark
    obj = SignalDigger(output_folder="hs300/%s" % name,
                       output_format='pdf')
    obj.process_signal_before_analysis(signal,
                                   price=price,
                                   n_quantiles=quantile, period=period,
                                   mask=mask,
                                   group=sw1,
                                   can_enter = enter,
                                   can_exit = exit,
                                   commission = 0.0008
                                   )
    obj.create_full_report()
    return obj

def plot_pfm(signal, name, period=5, quantile=5):
    obj = cal_obj(signal, name, period, quantile)
    plt.show()
def signal_data(signal, name, period=5, quantile=5):
    obj = cal_obj(signal, name, period, quantile)
    return obj.signal_data

signals_dict = {a:signal_data(neutralize_dict[a], a, 20) for a in alpha_signal} 

ic_pn = pd.Panel({a: analysis.ic_stats(signals_dict[a]) for a in signals_dict.keys()})

alpha_performance = round(ic_pn.minor_xs('return_ic'),2)
print(alpha_performance)

alpha_IR = alpha_performance.loc["Ann. IR"]
alpha_IC = alpha_performance.loc["IC Mean"]

good_alpha = alpha_IC[(alpha_IC>=0.03) & (alpha_IR>=0.25)]

good_alpha_dict = {g: float('%.2f' % good_alpha[g]) for g in good_alpha.index}

good_alpha_dict

Warning: signal与mask的index/columns不一致,请检查输入参数!
Warning: signal与can_enter的index/columns不一致,请检查输入参数!
Warning: signal与can_exit的index/columns不一致,请检查输入参数!
Warning: signal与group的index/columns不一致,请检查输入参数!
Warning: signal与price的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 49%


Value of signals of Different Quantiles Statistics
                   min       max      mean       std   count    count %
quantile
1        -1.509499e-02  0.000000 -0.001050  0.003340  122762  20.065347
2        -2.360623e-04  0.000000 -0.000116  0.000030  122376  20.002256
3        -1.231230e-04  0.000048 -0.000041  0.000026  122344  19.997025
4        -2.808087e-05  0.000147  0.000044  0.000035  122376  20.002256
5         5.421011e-20  0.010592  0.000228  0.000124  121953  19.933117
Figure saved: C:\Users\acer\hs300\gainvariance120\returns_report.pdf
Information Analysis
                 ic
IC Mean      -0.083
IC Std.       0.111
t-stat(IC)  -23.477
p-value(IC)   0.000
IC Skew       0.557
IC Kurtosis   0.852
Ann. IR      -0.748
Figure saved: C:\Users\acer\hs300\gainvariance120\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 53%


Value of signals of Different Quantiles Statistics
               min       max      mean       std   count    count %
quantile
1        -0.485714 -0.003079 -0.042117  0.027004  157393  20.063942
2        -0.169998  0.028884 -0.011469  0.008511  156876  19.998037
3        -0.105828  0.059690  0.001025  0.006110  156892  20.000076
4        -0.068465  0.128058  0.012090  0.008397  156876  19.998037
5        -0.030395  2.660048  0.042643  0.071490  156420  19.939907
Figure saved: C:\Users\acer\hs300\alpha46\returns_report.pdf
Information Analysis
                 ic
IC Mean       0.045
IC Std.       0.117
t-stat(IC)   13.289
p-value(IC)   0.000
IC Skew       0.499
IC Kurtosis   1.234
Ann. IR       0.385
Figure saved: C:\Users\acer\hs300\alpha46\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 53%


Value of signals of Different Quantiles Statistics
                  min         max        mean        std   count    count %
quantile
1        -1103.569252   26.567658 -147.340312  94.883089  157241  20.064158
2         -278.520259   47.224762  -30.656312  27.507585  156725  19.998316
3          -99.497461   90.349594   20.990840  19.536103  156738  19.999974
4          -45.057010  128.039110   58.330196  17.779721  156725  19.998316
5          -19.540721  490.764234   99.667075  28.397282  156262  19.939236
Figure saved: C:\Users\acer\hs300\alpha48\returns_report.pdf
Information Analysis
                ic
IC Mean      0.010
IC Std.      0.082
t-stat(IC)   4.196
p-value(IC)  0.000
IC Skew      0.220
IC Kurtosis  0.958
Ann. IR      0.121
Figure saved: C:\Users\acer\hs300\alpha48\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 52%


Value of signals of Different Quantiles Statistics
                 min         max       mean        std   count    count %
quantile
1        -123.529412   -2.512195 -31.833880  13.063672  155381  20.062882
2         -52.820000    8.885714 -17.580129   6.422993  154890  19.999484
3         -22.819672   31.294118  -5.607891   5.696526  154901  20.000904
4          -8.075000   58.042857  10.322398   9.965124  154890  19.999484
5          -1.115385  149.732394  46.540938  24.596352  154408  19.937247
Figure saved: C:\Users\acer\hs300\alpha85\returns_report.pdf
Information Analysis
                ic
IC Mean      0.012
IC Std.      0.070
t-stat(IC)   5.915
p-value(IC)  0.000
IC Skew      0.054
IC Kurtosis  0.896
Ann. IR      0.171
Figure saved: C:\Users\acer\hs300\alpha85\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Warning: signal与can_enter的index/columns不一致,请检查输入参数!
Warning: signal与can_exit的index/columns不一致,请检查输入参数!
Warning: signal与group的index/columns不一致,请检查输入参数!
Warning: signal与price的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 48%


Value of signals of Different Quantiles Statistics
                   min           max          mean           std   count  \
quantile
1        -1.871491e+08 -6.006206e+06 -2.457528e+07  1.966068e+07  142822
2        -1.168467e+08 -4.229557e+06 -1.464743e+07  9.779097e+06  142359
3        -6.178950e+07 -1.573442e+06 -8.873216e+06  6.576206e+06  142343
4        -2.911851e+07  8.518774e+07 -4.701053e+05  4.763836e+06  142359
5        -4.318198e+05  2.736451e+09  4.487741e+07  8.910403e+07  141885

            count %
quantile
1         20.065808
2         20.000759
3         19.998511
4         20.000759
5         19.934164
Figure saved: C:\Users\acer\hs300\vema12\returns_report.pdf
Information Analysis
                ic
IC Mean     -0.002
IC Std.      0.047
t-stat(IC)  -1.129
p-value(IC)  0.259
IC Skew      0.027
IC Kurtosis -0.013
Ann. IR     -0.033
Figure saved: C:\Users\acer\hs300\vema12\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Warning: signal与can_enter的index/columns不一致,请检查输入参数!
Warning: signal与can_exit的index/columns不一致,请检查输入参数!
Warning: signal与group的index/columns不一致,请检查输入参数!
Warning: signal与price的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 51%


Value of signals of Different Quantiles Statistics
               min       max      mean       std   count    count %
quantile
1        -0.545188 -0.026957 -0.141745  0.052457  143670  20.065026
2        -0.133735  0.017454 -0.054945  0.019989  143195  19.998687
3        -0.055189  0.066102 -0.002255  0.016814  143217  20.001760
4        -0.010170  0.164164  0.051473  0.022621  143195  19.998687
5         0.039051  0.539868  0.142213  0.058728  142745  19.935840
Figure saved: C:\Users\acer\hs300\ir60\returns_report.pdf
Information Analysis
                 ic
IC Mean      -0.058
IC Std.       0.136
t-stat(IC)  -14.453
p-value(IC)   0.000
IC Skew       0.099
IC Kurtosis  -0.064
Ann. IR      -0.429
Figure saved: C:\Users\acer\hs300\ir60\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Warning: signal与can_enter的index/columns不一致,请检查输入参数!
Warning: signal与can_exit的index/columns不一致,请检查输入参数!
Warning: signal与group的index/columns不一致,请检查输入参数!
Warning: signal与price的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 6%


Value of signals of Different Quantiles Statistics
                min        max      mean       std  count    count %
quantile
1        -21.838197   0.017801 -0.143773  0.553999  12658  20.462334
2         -0.090470   0.020294 -0.034788  0.011483  12348  19.961203
3         -0.043663   0.176810 -0.013045  0.008650  12377  20.008083
4         -0.011871   0.205674  0.010740  0.011459  12348  19.961203
5          0.000000  31.129011  0.122015  0.654505  12129  19.607177
Figure saved: C:\Users\acer\hs300\adminiexpenserate\returns_report.pdf
Information Analysis
                ic
IC Mean      0.020
IC Std.      0.266
t-stat(IC)   1.724
p-value(IC)  0.085
IC Skew      0.733
IC Kurtosis  4.503
Ann. IR      0.076
Figure saved: C:\Users\acer\hs300\adminiexpenserate\information_report.pdf
Warning: signal与mask的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 53%


Value of signals of Different Quantiles Statistics
                   min           max      mean       std   count    count %
quantile
1        -1.276896e+01 -1.324651e-01 -0.547528  0.818044  157265  20.063739
2        -4.295870e-01 -4.857226e-17 -0.130754  0.069252  156751  19.998163
3        -1.455869e-01  6.083848e-02 -0.010869  0.031505  156774  20.001097
4        -4.857226e-17  1.680875e-01  0.082426  0.032334  156751  19.998163
5         7.364187e-02  2.690597e+02  0.602196  6.204117  156286  19.938839

Figure saved: C:\Users\acer\hs300\ssctol\returns_report.pdf
Information Analysis
                ic
IC Mean      0.003
IC Std.      0.057
t-stat(IC)   1.689
p-value(IC)  0.091
IC Skew     -0.702
IC Kurtosis  1.889
Ann. IR      0.049
Figure saved: C:\Users\acer\hs300\ssctol\information_report.pdf
             adminiexpenserate  alpha46  alpha48  alpha85  gainvariance120  \
IC Mean                   0.02     0.05     0.01     0.01            -0.08
IC Std.                   0.27     0.12     0.08     0.07             0.11
t-stat(IC)                1.72    13.29     4.20     5.92           -23.48
p-value(IC)               0.09     0.00     0.00     0.00             0.00
IC Skew                   0.73     0.50     0.22     0.05             0.56
IC Kurtosis               4.50     1.23     0.96     0.90             0.85
Ann. IR                   0.08     0.38     0.12     0.17            -0.75

              ir60  ssctol  vema12
IC Mean      -0.06    0.00   -0.00
IC Std.       0.14    0.06    0.05
t-stat(IC)  -14.45    1.69   -1.13
p-value(IC)   0.00    0.09    0.26
IC Skew       0.10   -0.70    0.03
IC Kurtosis  -0.06    1.89   -0.01
Ann. IR      -0.43    0.05   -0.03

{'alpha46': 0.05}

In [20]:
#查看银子行业特点（最优周期）
signal_dict = {alpha : signal_data(dv.get_ts(alpha), alpha, period=20, quantile=5) for alpha in good_alpha.index}

def ic_length(signal, days=750):
    return signal.loc[signal.index.levels[0][-days]:]

from jaqs.research.signaldigger import performance as pfm

performance_dict = {}
for alpha in good_alpha.index:
    ic = pfm.calc_signal_ic(ic_length(signal_dict[alpha]), by_group=True)
    mean_ic_by_group = pfm.mean_information_coefficient(ic, by_group=True)
    performance_dict[alpha] = round(mean_ic_by_group,2)

ic_industry = pd.Panel(performance_dict).minor_xs('ic')

High_IC_Industry = pd.DataFrame([ic_industry[ic_industry>=0.05][alpha].dropna(how='all') for alpha in good_alpha.index]).T

Warning: signal与mask的index/columns不一致,请检查输入参数!
Nan Data Count (should be zero) : 0;  Percentage of effective data: 53%


Value of signals of Different Quantiles Statistics
               min       max      mean       std   count    count %
quantile
1         0.693307  1.204577  0.956985  0.036677  157393  20.063942
2         0.882151  1.238040  0.990219  0.028908  156876  19.998037
3         0.912844  1.315068  1.003940  0.031431  156892  20.000076
4         0.935711  1.405896  1.015527  0.035387  156876  19.998037
5         0.953078  3.701379  1.046774  0.083849  156420  19.939907
Figure saved: C:\Users\acer\hs300\alpha46\returns_report.pdf
Information Analysis
                ic
IC Mean      0.042
IC Std.      0.163
t-stat(IC)   8.947
p-value(IC)  0.000
IC Skew      0.410
IC Kurtosis  0.707
Ann. IR      0.259
Figure saved: C:\Users\acer\hs300\alpha46\information_report.pdf

In [21]:
#输出     八个因子，好因子就剩下一个alpha46
alpha46 = pd.Series({'name':'alpha46','data': ['close'],'IC':good_alpha_dict['alpha46'],'type':'191因子','market':'ZZ800','classify':'sw1','Formula':"(mean(close,3)+mean(close,6)+mean(close,12)+mean(close,24))/(4*close)",'parameter':[],'description':'3、6、12、24日均线价格之和与四倍当日收盘价的比值，理论为均线拉动上涨','High_IC_Industry': {indu: float('%.2f' % High_IC_Industry['alpha46'][indu]) for indu in High_IC_Industry['alpha46'].dropna().index}})
save_excel = pd.concat([globals()[name] for name in High_IC_Industry.columns],axis=1,keys=High_IC_Industry.columns).T
save_excel.to_excel('Finish_alpha.xlsx')